### ISSUE TITLE
There is no readme there as described.

### ISSUE THREAD

**Issue by miqianmimi** [PCCproject/PCC-RL#1]
There is no readme there ./src/gym/online/README.md for detailed instructions on how to load trained models. Could the author tell how to test the trained model by using the PCC-Uspace

**Comment by ghost** [comment]
Thanks for the authors' good job,but there is no ./src/gym/online/README.md file!could you please add this file so make it convenient for beginners.

**Comment by nathanhjay** [comment]
I should have a solution for you shortly. It looks like the specific branch of the PCC-Uspace repo with code for running python modules isn't well documented, but I'll add that documentation and the docs here and get back to you.

**Comment by nathanhjay** [comment]
Readme provided. Let me know if you have any more trouble getting it up and running. I'll leave this issue open for a few days in case anything needs clarification or doesn't seem to work as expected w.r.t. the Readme instructions.
