### ISSUE TITLE
About stable_solve.py default setting and rewards

### ISSUE THREAD

**Issue by kim95175** [PCCproject/PCC-RL#11]
Hi. 

I checked your model on #5 and found that it works well

when i run your code in default setting ( nothing changed ), rewards don't grow.
how to train model like yours with stable_solve.py? 

Thanks.

**Comment by r02b** [comment]
Hi,
Our model was trained using the parameters as they appear in the default setting. Rewards not growing at all over a long period of time (how many epochs did you use to train? It takes a while for the reward to start improving significantly) indicates the model is not learning at all, but that could be for a number of reasons - I'd first check your settings are correct, the model path is set right, etc.
