### ISSUE TITLE
Where is this stable_baselines file?

### ISSUE THREAD

**Issue by Mrhs121** [PCCproject/PCC-RL#14]

**Comment by Mrhs121** [comment]
from stable_baselines.common.policies import MlpPolicy
from stable_baselines.common.policies import FeedForwardPolicy
from stable_baselines import PPO1

This stable_baselines file is not in the repo

**Comment by r02b** [comment]
Stable baselines is an open-source package. See more here:
https://stable-baselines.readthedocs.io/en/master/
