### ISSUE TITLE
The trained model's rate is always Approximately equal to MIN_RATE in loaded_client.py

### ISSUE THREAD

**Issue by LiYufengzz** [PCCproject/PCC-RL#16]
I tested the trained model by using ./app/pccclient send 127.0.0.1 9000 --pcc-rate-control=python -pyhelper=loaded_client -pypath=/path/to/pcc-rl/src/udt-plugins/testing/ --history-len=10 --pcc-utility-calc=linear --model-path=/path/to/your/model/
But the send rate can't exceed 0.5 Mbps.While I changed the MIN_RATE in loaded_client.py to 5, the send rate can't exceed 5Mbps then. I wonder what's wrong with it,thanks.
<img width="549" alt="send rate" src="https://user-images.githubusercontent.com/26202915/124741079-ed33c180-df4d-11eb-9ec8-b160b23dabe7.png">

**Comment by jialianchen** [comment]
hello!i meet the same problem with you  .i wonder whether you solve it!

**Comment by LiYufengzz** [comment]
I used two machines to run this script,and the problem was solved.



---Original---
From: ***@***.***&gt;
Date: Mon, Jul 26, 2021 10:47 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PCCproject/PCC-RL] The trained model's rate is always Approximately equal to MIN_RATE in loaded_client.py (#16)




 
hello!i meet the same problem with you  .i wonder whether you solve it!

**Comment by r02b** [comment]
As this seems to be a bootstrapping problem rather than a bug, I'm closing this issue.
