### ISSUE TITLE
the most important part of this project(use gym model as CC in UDT) can not be run!

### ISSUE THREAD

**Issue by ghost** [PCCproject/PCC-RL#2]
the most important part of this project(use gym model as CC in UDT) can not be run!

**Comment by nathanhjay** [comment]
It looks like this is partially a cross issue with a development branch of the PCC-Uspace repository. I'll add a specific branch of that repo that can be used to run this code, update the READMEs and let you know.

**Comment by nathanhjay** [comment]
I provided the necessary Readme files. I'm closing this issue but leaving #1 open for any continued issues with Readme instructions.
