### ISSUE TITLE
there is no code and deep-learning branch of PCC-Uspace as you stated

### ISSUE THREAD

**Issue by TheRisingStar** [PCCproject/PCC-RL#4]
There is no PCCProject/PCC-Uspace.git repo with the deep-learning branch checked out.
I wonder if you really finish the experience.

**Comment by LiYufengzz** [comment]
I have the same question with you.Did you test the saved_model by PCC-Uspace successfully afterwards?

**Comment by TheRisingStar** [comment]
Yes, I do.&nbsp; If you are pleased, you can add my wechat "zjh5544238" for further discuss.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月6日(星期二) 下午5:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [PCCproject/PCC-RL] there is no code and deep-learning branch of PCC-Uspace as you stated (#4)





 
I have the same question with you.Did you test the saved_model by PCC-Uspace successfully afterwards?
