### ISSUE TITLE
No trained model

### ISSUE THREAD

**Issue by salma-emara** [PCCproject/PCC-RL#5]
Hello Authors,

Thank you for your efforts in putting the source code online. But I have a question. I could not find the trained model to test it nor was Aurora added to pantheon as PCC and PCC Vivace. So may you provide us with the trained model at least?

Thank you in advance

**Comment by nathanhjay** [comment]
Yea, I can add a directory with the trained Aurora model from the paper. I'll update and close this once that's done.

**Comment by Suhaibinator** [comment]
Hi Nathan,

Was just wondering if you'd had a chance to upload the trained Aurora model yet?

**Comment by r02b** [comment]
Hi all,

I'm attaching the trained model here for your convenience.
[icml_paper_model.zip](https://github.com/PCCproject/PCC-RL/files/4016454/icml_paper_model.zip)

**Comment by idoyehe** [comment]
THX

**Comment by TergelMunkhbat** [comment]
Hi all,

this model gives me the below error when I run tests. How could I solve the issue?

google.protobuf.text_format.ParseError: 76:21 : '              type: DT_UINT32': Enum type "tensorflow.DataType" has no value named DT_UINT32.

Looking forward to hearing from you.
@r02b @nathanhjay

**Comment by TergelMunkhbat** [comment]
Hello folks,

I am conducting some experiments based on the model attached by @r02b. However, the throughput cannot exceed more than 0.5 Mbps. Could you please help me to figure out it? Thank you in advance.

**tergel@congestion-control:~/RL/PCC-Uspace/src$ app/pccclient send ulsan 5003 --pcc-rate-control=python -pyhelper=loaded_client -pypath=/home/tergel/Test/RL/PCC-RL/src/udt-plugins/testing/ --history-len=10 --pcc-utility-calc=linear --model-path=/home/tergel/RL/PCC-Uspace/src/ICML_training_model/icml_paper_model/**
Starting sending rate = 2.24e+06
2021-03-02 15:19:00.117791: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/tergel/RL/PCC-Uspace/src/core
2021-03-02 15:19:00.117820: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2021-03-02 15:19:00.117837: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (congestion-control): /proc/driver/nvidia/version does not exist
2021-03-02 15:19:00.118395: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2021-03-02 15:19:00.143709: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2900000000 Hz
2021-03-02 15:19:00.144754: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55eed27df4c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-03-02 15:19:00.144772: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:From /home/tergel/Test/RL/PCC-RL/src/udt-plugins/testing/loaded_agent.py:25: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
connect
finished connect
        Rate (Mbps)     RTT (ms)        Sent            Lost
Begining of the data send
1       0               10000           0               0
2       0               10000           0               0
End of the data send
0       1410065408
145600000       1410065408
Begining of the data send
3       3.62224         5.24698         311             0
4       1.49082         5.24526         439             0
5       0.885169                5.24785         515             0
6       0.617292                5.22444         568             0
7       0.500824                5.29394         611             0
8       0.489168                5.28796         653             0
9       0.477526                5.25476         694             0
10      0.489174                5.23419         736             0
11      0.489176                5.21565         778             0
12      0.47753         5.28155         819             0
13      0.489176                5.23707         861             0
14      0.489179                5.20155         903             0
15      0.477531                5.26266         944             0
16      0.489178                5.26317         986             0
17      0.489178                9.91258         1028            0
18      0.477531                10.8524         1069            0
19      0.489176                5.75902         1111            0
20      0.489176                5.80497         1153            0
21      0.477531                6.59316         1194            0
22      0.489176                8.03863         1236            0
23      0.489179                8.08277         1278            0
24      0.477532                8.11315         1319            0
25      0.48918         8.70412         1361            0
26      0.489179                5.87617         1403            0
27      0.477533                6.12219         1444            0
28      0.489177                7.04131         1486            0
29      0.489177                7.99061         1528            0
30      0.477531                10.4724         1569            0
31      0.489177                5.26468         1611            0
32      0.489177                5.2363          1653            0
33      0.477529                5.62193         1694            0
34      0.489181                7.06206         1736            0
...

@nathanhjay

**Comment by r02b** [comment]
Closing the issue - model provided in the comments, if there are any issues with it, a new issue should be opened.
