### ISSUE TITLE
About training time

### ISSUE THREAD

**Issue by wushilan** [PCCproject/PCC-RL#7]
Hi:
   When I try to run stable_solve.py in PCC_RL/src/gym. I found that rewards don't grow or converg. How long does it need to converge?
  Best wishes

**Comment by tianbochen1** [comment]
I suppose that this is because the initial state of each episode is different.

**Comment by Syzygianinfern0** [comment]
> I suppose that this is because the initial state of each episode is different.

Shouldn't it be that way by default so that the model generalizes to all cases?

**Comment by chenxi-yang** [comment]
Hi, 

I met the same problem. I am able to make the learning converge with a simpler setting of the environment, but can not get the reward in the paper. Did you find a solution to this?

**Comment by Syzygianinfern0** [comment]
> Hi,
> 
> I met the same problem. I am able to make the learning converge with a simpler setting of the environment, but can not get the reward in the paper. Did you find a solution to this?

I suspect it is not possible to get the reward from the paper directly from the given codes due to this line: 

https://github.com/PCCproject/PCC-RL/blob/64bea6eeee3a3e558449c35b6496cf596f5ded52/src/gym/network_sim.py#L39

A scaled version of the reward is what is used by the code.

**Comment by Syzygianinfern0** [comment]
Although, I am not sure and I have not fixed the issue as well.

**Comment by chenxi-yang** [comment]
Did you make it work? I actually had two issues
1. The default setting can not converge.
2. I simplified the environment setting (super simple bw, lat) and got a reward of around 600. The reported reward is around 6000, which is not REWARD_SCALE * 600.

**Comment by Syzygianinfern0** [comment]
@cxyang1997 No, I have not been able to achieve the reported rewards.

**Comment by chenxi-yang** [comment]
@Syzygianinfern0 Hi, thanks for letting me know! May I ask if you achieve the reported rewards with the model provided in #5? Thanks!

**Comment by Syzygianinfern0** [comment]
> @Syzygianinfern0 Hi, thanks for letting me know! May I ask if you achieve the reported rewards with the model provided in #5? Thanks!

Nope, I think I was unable to.

**Comment by chenxi-yang** [comment]
Thank you for letting me know!
